/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebSocketV1MessageEnvelope =
  | CreateGame
  | GameCreated
  | JoinGame
  | RejoinGame
  | GameStart
  | GameState
  | Move
  | MoveMade
  | Error;
export type Color = "white" | "black";
export type Promotion = "Q" | "R" | "B" | "N" | "U";
export type ErrorCode =
  | "invalid_message"
  | "already_in_game"
  | "invalid_game"
  | "game_full"
  | "invalid_rejoin"
  | "invalid_move"
  | "game_not_started"
  | "wrong_turn";

export interface CreateGame {
  type: "create_game";
}
export interface GameCreated {
  type: "game_created";
  gameId: string;
  color: Color;
}
export interface JoinGame {
  type: "join_game";
  gameId: string;
}
export interface RejoinGame {
  type: "rejoin_game";
  gameId: string;
  color: Color;
}
export interface GameStart {
  type: "game_start";
  color: Color;
  initialPosition?: string;
}
export interface GameState {
  type: "game_state";
  color: Color;
  started: boolean;
  moves: MoveRecord[];
}
export interface MoveRecord {
  by: Color;
  from: string;
  to: string;
  promotion?: Promotion;
}
export interface Move {
  type: "move";
  from: string;
  to: string;
  promotion?: Promotion;
}
export interface MoveMade {
  type: "move_made";
  by: Color;
  from: string;
  to: string;
  promotion?: Promotion;
}
export interface Error {
  type: "error";
  code: ErrorCode;
  message: string;
}
