/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebSocketV1MessageEnvelope =
  | CreateGame
  | GameCreated
  | JoinGame
  | GameJoined
  | RejoinGame
  | GameStart
  | GameState
  | Move
  | MoveMade
  | Presence
  | Error;
/**
 * Random id a browser tab picks for itself. The server remembers which tab claimed each seat, so a tab can re-send a join whose answer it lost, and an automatic rejoin can tell its own stale connection from another tab's live one.
 */
export type ClientId = string;
export type Color = "white" | "black";
export type Promotion = "Q" | "R" | "B" | "N" | "U";
export type ErrorCode =
  | "invalid_message"
  | "already_in_game"
  | "invalid_game"
  | "game_full"
  | "invalid_rejoin"
  | "invalid_move"
  | "game_not_started"
  | "wrong_turn"
  | "seat_in_use";

export interface CreateGame {
  type: "create_game";
  clientId?: ClientId;
}
export interface GameCreated {
  type: "game_created";
  gameId: string;
  color: Color;
}
export interface JoinGame {
  type: "join_game";
  gameId: string;
  clientId?: ClientId;
}
export interface GameJoined {
  type: "game_joined";
  color: Color;
}
export interface RejoinGame {
  type: "rejoin_game";
  gameId: string;
  color: Color;
  clientId?: ClientId;
  /**
   * Whether to take the seat from another tab's live connection (the default). An automatic reconnect sends false, and is refused with seat_in_use instead.
   */
  takeover?: boolean;
}
export interface GameStart {
  type: "game_start";
  color: Color;
}
export interface GameState {
  type: "game_state";
  color: Color;
  started: boolean;
  moves: MoveRecord[];
}
export interface MoveRecord {
  by: Color;
  from: string;
  to: string;
  promotion?: Promotion;
}
export interface Move {
  type: "move";
  from: string;
  to: string;
  promotion?: Promotion;
}
export interface MoveMade {
  type: "move_made";
  by: Color;
  from: string;
  to: string;
  promotion?: Promotion;
}
export interface Presence {
  type: "presence";
  color: Color;
  online: boolean;
}
export interface Error {
  type: "error";
  code: ErrorCode;
  message: string;
}
