/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebSocketV1MessageEnvelope =
  | CreateGame
  | GameCreated
  | LookGame
  | GameInfo
  | JoinGame
  | GameJoined
  | RejoinGame
  | GameStart
  | GameState
  | Move
  | MoveMade
  | Resign
  | OfferDraw
  | AcceptDraw
  | DeclineDraw
  | DrawOffered
  | DrawDeclined
  | GameEnded
  | Presence
  | Error;
/**
 * Random id a browser tab picks for itself. The server remembers which tab claimed each seat, so a tab can re-send a join whose answer it lost, and an automatic rejoin can tell its own stale connection from another tab's live one.
 */
export type ClientId = string;
export type Color = "white" | "black";
export type Promotion = "Q" | "R" | "B" | "N" | "U";
/**
 * How a game ended by the players' own decision rather than on the board: one side resigned, or both agreed a draw.
 */
export type EndingResult = "resignation" | "agreement";
export type ErrorCode =
  | "invalid_message"
  | "already_in_game"
  | "invalid_game"
  | "game_full"
  | "invalid_rejoin"
  | "invalid_move"
  | "game_not_started"
  | "wrong_turn"
  | "seat_in_use"
  | "game_over"
  | "invalid_draw";

export interface CreateGame {
  type: "create_game";
  clientId?: ClientId;
  /**
   * The side the creator wants to play. Omitted, the server picks one at random.
   */
  color?: "white" | "black";
}
export interface GameCreated {
  type: "game_created";
  gameId: string;
  color: Color;
}
/**
 * Asks which seats of a game are taken, without joining it: what an invitation shows before the player accepts.
 */
export interface LookGame {
  type: "look_game";
  gameId: string;
}
export interface GameInfo {
  type: "game_info";
  gameId: string;
  /**
   * The seats already claimed, in the order they were taken.
   */
  seats: Color[];
}
export interface JoinGame {
  type: "join_game";
  gameId: string;
  clientId?: ClientId;
}
export interface GameJoined {
  type: "game_joined";
  color: Color;
}
export interface RejoinGame {
  type: "rejoin_game";
  gameId: string;
  color: Color;
  clientId?: ClientId;
  /**
   * Whether to take the seat from another tab's live connection (the default). An automatic reconnect sends false, and is refused with seat_in_use instead.
   */
  takeover?: boolean;
}
export interface GameStart {
  type: "game_start";
  color: Color;
}
export interface GameState {
  type: "game_state";
  color: Color;
  started: boolean;
  moves: MoveRecord[];
  ending?: Ending;
  drawOffer?: DrawOffer;
}
export interface MoveRecord {
  by: Color;
  from: string;
  to: string;
  promotion?: Promotion;
}
/**
 * Set once the game has ended by resignation or agreement.
 */
export interface Ending {
  result: EndingResult;
  /**
   * The side that won: the resigning side's opponent. Absent for an agreed draw.
   */
  winner?: "white" | "black";
}
/**
 * The latest draw offer, if any; it stands only if its ply is the number of moves and it was not declined.
 */
export interface DrawOffer {
  by: Color;
  ply: number;
  /**
   * The opponent declined it. A draw can be offered once per move.
   */
  declined?: boolean;
}
export interface Move {
  type: "move";
  from: string;
  to: string;
  promotion?: Promotion;
}
export interface MoveMade {
  type: "move_made";
  by: Color;
  from: string;
  to: string;
  promotion?: Promotion;
}
/**
 * The sender resigns: the opponent wins.
 */
export interface Resign {
  type: "resign";
}
/**
 * The sender offers a draw.
 */
export interface OfferDraw {
  type: "offer_draw";
}
/**
 * The sender accepts the opponent's standing draw offer.
 */
export interface AcceptDraw {
  type: "accept_draw";
}
/**
 * The sender declines the opponent's standing draw offer.
 */
export interface DeclineDraw {
  type: "decline_draw";
}
/**
 * To both players: `by` offered a draw when `ply` moves had been played.
 */
export interface DrawOffered {
  type: "draw_offered";
  by: Color;
  ply: number;
}
/**
 * To both players: `by` declined the draw offered when `ply` moves had been played.
 */
export interface DrawDeclined {
  type: "draw_declined";
  by: Color;
  ply: number;
}
/**
 * To both players: the game ended by resignation or agreement. No move, offer or resignation is accepted after it.
 */
export interface GameEnded {
  type: "game_ended";
  result: EndingResult;
  /**
   * The side that won; absent for an agreed draw.
   */
  winner?: "white" | "black";
}
export interface Presence {
  type: "presence";
  color: Color;
  online: boolean;
}
export interface Error {
  type: "error";
  code: ErrorCode;
  message: string;
}
