// Writes src/three/pieces/knight.medium.ts: the medium set's sculpted knight
// (head, mane and eyes), built here once so the game can load its bytes
// instead of sculpting it in the browser. Run it after changing the knight
// (knight.ts, sdf.ts, decimate.ts or the medium detail in set.ts); a unit
// test fails while the file is stale.
//   npm run bake:knight
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildKnight } from '../src/three/pieces/knight';
import { encodeKnight } from '../src/three/pieces/knightData';
import { DETAIL } from '../src/three/pieces/set';

const { step, knight } = DETAIL.medium;
const data = encodeKnight(buildKnight(step, knight));
const out = fileURLToPath(new URL('../src/three/pieces/knight.medium.ts', import.meta.url));
writeFileSync(
  out,
  `// Generated by \`npm run bake:knight\` (scripts/bake-knight.ts): the medium
// knight's sculpted meshes, byte for byte. Do not edit; knightData.test.ts
// fails when it no longer matches a fresh build.
import type { KnightData } from './knightData';

export const KNIGHT_MEDIUM: KnightData = {
  counts: [${data.counts.join(', ')}],
  base64:
    '${data.base64}',
};
`,
);
console.log(`wrote ${out} (${data.base64.length} base64 characters)`);
