// Writes the medium set's precomputed parts, so the game can load their bytes
// instead of working them out in the browser:
//   src/three/pieces/knight.medium.ts   the sculpted knight (head, mane, eyes)
//   src/three/scene/occlusion.medium.ts every piece's baked occlusion
// Run it after changing a piece's shape (anything in src/three/pieces, or
// the occlusion bake in scene/occlusion.ts); knightData.test.ts and
// occlusionData.test.ts fail while either file is stale.
//   npm run bake:pieces
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PieceType } from '../src/engine/pieces';
import { buildKnight } from '../src/three/pieces/knight';
import { encodeKnight } from '../src/three/pieces/knightData';
import { DETAIL, pieceSet } from '../src/three/pieces/set';
import { occlusionOfPiece } from '../src/three/scene/occlusion';
import { encodeOcclusion } from '../src/three/scene/occlusionData';

const write = (path: string, text: string) => {
  const out = fileURLToPath(new URL(path, import.meta.url));
  writeFileSync(out, text);
  console.log(`wrote ${out}`);
};
const header = (what: string, test: string) =>
  `// Generated by \`npm run bake:pieces\` (scripts/bake-pieces.ts): ${what}, byte
// for byte. Do not edit; ${test} fails when it no longer matches a fresh build.
`;

const { step, knight } = DETAIL.medium;
const k = encodeKnight(buildKnight(step, knight));
write(
  '../src/three/pieces/knight.medium.ts',
  `${header("the medium knight's sculpted meshes", 'knightData.test.ts')}import type { KnightData } from './knightData';

export const KNIGHT_MEDIUM: KnightData = {
  counts: [${k.counts.join(', ')}],
  base64:
    '${k.base64}',
};
`,
);

// The set as built here sculpts its knight: the same bytes as the file above
const set = pieceSet();
const occlusion = {} as Record<PieceType, Float32Array[]>;
for (const type of Object.values(PieceType)) occlusion[type] = occlusionOfPiece(set[type]);
const o = encodeOcclusion(occlusion);
write(
  '../src/three/scene/occlusion.medium.ts',
  `${header("the medium set's baked occlusion", 'occlusionData.test.ts')}import type { OcclusionData } from './occlusionData';

export const OCCLUSION_MEDIUM: OcclusionData = {
  counts: {
${Object.values(PieceType)
  .map((t) => `    ${t}: [${o.counts[t].join(', ')}],`)
  .join('\n')}
  },
  base64:
    '${o.base64}',
};
`,
);
