# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Color(Enum):
    white = 'white'
    black = 'black'


class Promotion(Enum):
    Q = 'Q'
    R = 'R'
    B = 'B'
    N = 'N'
    U = 'U'


class ErrorCode(Enum):
    invalid_message = 'invalid_message'
    already_in_game = 'already_in_game'
    invalid_game = 'invalid_game'
    game_full = 'game_full'
    invalid_rejoin = 'invalid_rejoin'
    invalid_move = 'invalid_move'
    game_not_started = 'game_not_started'
    wrong_turn = 'wrong_turn'


class CreateGame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['create_game']


class GameCreated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['game_created']
    gameId: str
    color: Color


class JoinGame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['join_game']
    gameId: str


class RejoinGame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['rejoin_game']
    gameId: str
    color: Color


class GameStart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['game_start']
    color: Color
    initialPosition: Optional[str] = None


class MoveRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    by: Color
    from_: constr(pattern=r'^[A-E][a-e][1-5]$') = Field(..., alias='from')
    to: constr(pattern=r'^[A-E][a-e][1-5]$')
    promotion: Optional[Promotion] = None


class Move(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['move']
    from_: constr(pattern=r'^[A-E][a-e][1-5]$') = Field(..., alias='from')
    to: constr(pattern=r'^[A-E][a-e][1-5]$')
    promotion: Optional[Promotion] = None


class MoveMade(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['move_made']
    by: Color
    from_: constr(pattern=r'^[A-E][a-e][1-5]$') = Field(..., alias='from')
    to: constr(pattern=r'^[A-E][a-e][1-5]$')
    promotion: Optional[Promotion] = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    code: ErrorCode
    message: str


class GameState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['game_state']
    color: Color
    started: bool
    moves: List[MoveRecord]


class WebsocketV1MessageEnvelope(
    RootModel[
        Union[
            CreateGame,
            GameCreated,
            JoinGame,
            RejoinGame,
            GameStart,
            GameState,
            Move,
            MoveMade,
            Error,
        ]
    ]
):
    root: Union[
        CreateGame,
        GameCreated,
        JoinGame,
        RejoinGame,
        GameStart,
        GameState,
        Move,
        MoveMade,
        Error,
    ] = Field(..., title='WebSocket V1 Message Envelope')
