# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-08-08T21:16:46+00:00
#   command:   datamodel-codegen --input server/schema.json --input-file-type jsonschema --output server/messages.py --output-model-type pydantic_v2.BaseModel

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class CreateGame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['create_game']


class Color(Enum):
    white = 'white'
    black = 'black'


class GameCreated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['game_created']
    gameId: str
    color: Color


class JoinGame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['join_game']
    gameId: str


class RejoinGame(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['rejoin_game']
    gameId: str
    color: Color


class GameStart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['game_start']
    color: Color
    initialPosition: str | None = None


class By(Enum):
    white = 'white'
    black = 'black'


class Promotion(Enum):
    Q = 'Q'
    R = 'R'
    B = 'B'
    N = 'N'
    U = 'U'


class MoveRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    by: By
    from_: constr(pattern=r'^[A-E][a-e][1-5]$') = Field(..., alias='from')
    to: constr(pattern=r'^[A-E][a-e][1-5]$')
    promotion: Promotion | None = None


class Move(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['move']
    from_: constr(pattern=r'^[A-E][a-e][1-5]$') = Field(..., alias='from')
    to: constr(pattern=r'^[A-E][a-e][1-5]$')
    promotion: Promotion | None = None


class MoveMade(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['move_made']
    by: By
    from_: constr(pattern=r'^[A-E][a-e][1-5]$') = Field(..., alias='from')
    to: constr(pattern=r'^[A-E][a-e][1-5]$')
    promotion: Promotion | None = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    code: str
    message: str


class GameState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['game_state']
    color: Color
    started: bool
    moves: list[MoveRecord]


class WebsocketV1MessageEnvelope(
    RootModel[
        CreateGame
        | GameCreated
        | JoinGame
        | RejoinGame
        | GameStart
        | GameState
        | Move
        | MoveMade
        | Error
    ]
):
    root: (
        CreateGame
        | GameCreated
        | JoinGame
        | RejoinGame
        | GameStart
        | GameState
        | Move
        | MoveMade
        | Error
    ) = Field(..., title='WebSocket V1 Message Envelope')
