name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: cd client && npm ci
      - name: Run linter
        run: cd client && npm run lint
      - name: Build
        run: cd client && npm run build
      - name: Run tests with coverage
        run: cd client && npm run test -- --coverage
      - name: Install Playwright Browsers
        run: cd client && npx playwright install --with-deps
      - name: Start Vite dev server
        run: cd client && npm run dev &
      - name: Wait for dev server
        run: npx wait-on http://localhost:5173
      - name: Run Playwright E2E tests
        run: cd client && npm run e2e
